name: Hourly Yle scrape

on:
  schedule:
    - cron: "0 * * * *" # hourly (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright (Chromium + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run scraper (with simple retry)
        run: |
          set -e
          for i in 1 2 3; do
            npm run scrape && break || sleep 10
          done
